apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: database
type: Opaque
data:
  root-username: YWRtaW4=  # base64 for "admin"
  root-password: cGFzc3dvcmQ=  # base64 for "password"
  mongo-auth-db: bWFpbl9kYgo=  # base64 for "main_db"