{{- if .Values.ingress.enabled -}}
{{- $baseDomain := trimPrefix "www." .Values.env.domainUrl -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/server-alias: {{ .Values.env.domainUrl | quote }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ $baseDomain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: {{ .Values.service.port }}
  - host: {{ .Values.env.domainUrl }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: {{ .Values.service.port }}
{{- end }}
