apiVersion: v1
kind: Namespace
metadata:
  name: frontend

---

apiVersion: v1
kind: Namespace
metadata:
  name: backend

---

apiVersion: v1
kind: Namespace
metadata:
  name: database

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-deployer-app
  namespace: argocd

---

apiVersion: v1
kind: Secret 
metadata: 
  name: argocd-deployer-app-sa
  namespace: argocd
  annotations: 
    kubernetes.io/service-account.name: argocd-deployer-app
type: kubernetes.io/service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-deployer-app
  namespace: frontend
rules:
- apiGroups: ["*"]
  resources:
  - pods
  - services
  - deployments
  - configmaps
  - secrets
  - ingresses
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-deployer-rolebinding-app
  namespace: frontend
subjects:
- kind: ServiceAccount
  name: argocd-deployer-app
  namespace: argocd
roleRef:
  kind: Role
  name: argocd-deployer-app
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-deployer-app
  namespace: backend
rules:
- apiGroups: ["*"]
  resources:
  - pods
  - services
  - deployments
  - configmaps
  - secrets
  - ingresses
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-deployer-rolebinding-app
  namespace: backend
subjects:
- kind: ServiceAccount
  name: argocd-deployer-app
  namespace: argocd
roleRef:
  kind: Role
  name: argocd-deployer-app
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-deployer-app
  namespace: database
rules:
- apiGroups: ["*"]
  resources:
  - pods
  - services
  - deployments
  - configmaps
  - secrets
  - ingresses
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-deployer-rolebinding-app
  namespace: backend
subjects:
- kind: ServiceAccount
  name: argocd-deployer-app
  namespace: argocd
roleRef:
  kind: Role
  name: argocd-deployer-app
  apiGroup: rbac.authorization.k8s.io