apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-deployer-admin
  namespace: argocd

---

apiVersion: v1
kind: Secret 
metadata: 
  name: argocd-deployer-admin-sa
  namespace: argocd
  annotations: 
    kubernetes.io/service-account.name: argocd-deployer-admin
type: kubernetes.io/service-account-token

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-deployer-admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-deployer-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-deployer-admin
subjects:
- kind: ServiceAccount
  name: argocd-deployer-admin-sa
  namespace: argocd

