apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jaintpharsha/mern_3tire.git
    targetRevision: main
    path: k8s/frontend/frontend-chart
    helm:
      valueFiles:
        - values.yaml
      values: |
        image:
          repository: harshajain/frontend
          tag: latest
        env:
          backendUrl: "https://backend.acadcart.com"
          domainUrl: "www.acadcart.com"
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  serviceAccountName: argocd-deployer-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

