replicaCount: 2

image:
  repository: harshajain/backend
  tag: latest
  pullPolicy: Always

domain: acadcart.com

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

env:
  mongoHost: mongo.database.svc.cluster.local
  mongoPort: "27017"

secret:
  appSecrets:
    jwtSecret: c3VwZXJfc2VjcmV0X2tleQ==
  mongoSecrets:
    # MongoDB credentials (must match database namespace credentials)
    rootUsername: YWRtaW4=              # base64 for "admin"
    rootPassword: cGFzc3dvcmQ=          # base64 for "password"
       
    # References to keys in mongo-secret
    secretName: mongo-secret
    usernameKey: root-username
    passwordKey: root-password
    authDbKey: mongo-auth-db
database:
  name: srv-db 