apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.className }}
provisioner: ebs.csi.aws.com
volumeBindingMode: {{ .Values.storage.volumeBindingMode }}
reclaimPolicy: {{ .Values.storage.reclaimPolicy }}
allowVolumeExpansion: true
parameters:
  type: {{ .Values.storage.parameters.type }}
fsType: {{ .Values.storage.parameters.fsType }}
