apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.className }}
provisioner: ebs.csi.aws.com
volumeBindingMode: {{ .Values.storage.volumeBindingMode }}
parameters:
  type: {{ .Values.storage.parameters.type }}
  fsType: {{ .Values.storage.parameters.fsType }}
  iops: {{ .Values.storage.parameters.iops | quote }}
  throughput: {{ .Values.storage.parameters.throughput | quote }}
allowVolumeExpansion: true
reclaimPolicy: {{ .Values.storage.reclaimPolicy }}
